name = "mayko"
pages_build_output_dir = "./dist"
compatibility_date = "2024-09-25"

# Environment Variables & Secrets
[vars]
ADMIN_PASSWORD = "Doxish44_"

# D1 SQLite Database Binding
[[d1_databases]]
binding = "DB"
database_name = "mayko-db"
database_id = "4541a2c0-53bb-4ad9-b0c8-8379e0c7fbc9"

# KV Namespace Binding
[[kv_namespaces]]
binding = "MAYKO_KV"
id = "c656498daed746b5bd33a6e8a1ee11e2"
